import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Android build. "build/**" above only covers the top level,
    // so without these Gradle's intermediates get linted and drown out real
    // warnings with thousands of lines of machine-written JavaScript.
    "android/**",
    "capacitor.config.ts",
  ]),
]);

export default eslintConfig;
